title: "我的技术栈"
description: "用技术撑起这片天"
author: "李春华"
github: https://github.com/eddy2lee
about: 我是一名互联网产品开发者，专注于NodeJs全栈、PHP全栈以及H5应用等开发"
disqus_shortname: eddylee
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/eddy2lee"

urls:
    - text: "关于我"
      url: /about/
    - text: "我的项目"
      url: /projects/
    - text: "RSS订阅"
      url: /feed.xml

url: "http://eddylee.cc"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
